18

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -5,7 +5,7 @@ on:
     branches:
       - main
       - feature/github_actions
-      
+
 permissions:
   contents: write
 
@@ -58,6 +58,7 @@ jobs:
           asset_name: laba3-0.0.${{ github.run_number }}-Linux.deb
           asset_content_type: application/vnd.debian.binary-package
 
+
   build_macos:
     runs-on: macos-latest
     permissions: write-all
@@ -66,7 +67,7 @@ jobs:
         with:
           submodules: true
       
-      - name: Install dependencies
+      - name: Install CMake with productbuild support
         run: brew install cmake
 
       - name: Configure with CMake
@@ -78,10 +79,10 @@ jobs:
       - name: Create package
         run: cmake --build . --target package
 
-      - name: Verify DMG file
+      - name: Verify .pkg file
         run: |
-          if [ ! -f ./laba3-0.0.${{ github.run_number }}-macos.dmg ]; then
-            echo "Error: .dmg file not found!" >&2
+          if [ ! -f ./laba3-0.0.${{ github.run_number }}-macos.pkg ]; then
+            echo "Error: .pkg file not found!" >&2
             exit 1
           fi
 
@@ -103,6 +104,6 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create_release_macos.outputs.upload_url }}
-          asset_path: ./laba3-0.0.${{ github.run_number }}-macos.dmg
-          asset_name: laba3-0.0.${{ github.run_number }}-macos.dmg
-          asset_content_type: application/x-apple-diskimage
+          asset_path: ./laba3-0.0.${{ github.run_number }}-macos.pkg
+          asset_name: laba3-0.0.${{ github.run_number }}-macos.pkg
+          asset_content_type: application/x-apple-installer-package
