13

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -29,8 +29,12 @@ jobs:
       - name: List files
         run: ls -la
 
-      - name: Rename package
-        run: mv ./laba3-*.deb ./laba3-0.0.${{ github.run_number }}-Linux.deb
+      - name: Rename package (Linux)
+        run: |
+          DEB_FILE=$(ls ./laba3-*.deb)
+          if [ "$DEB_FILE" != "./laba3-0.0.${{ github.run_number }}-Linux.deb" ]; then
+            mv "$DEB_FILE" ./laba3-0.0.${{ github.run_number }}-Linux.deb
+          fi
 
       - name: Create Release (Ubuntu)
         id: create_release_ubuntu
@@ -44,7 +48,7 @@ jobs:
           prerelease: false
 
       - name: Upload Release Asset (Ubuntu)
-        id: upload-release-asset-ubuntu
+        id: upload_release_asset_ubuntu
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -62,14 +66,23 @@ jobs:
       - uses: actions/checkout@v3
         with:
           submodules: true
+      
       - name: Configure with CMake
         run: cmake . -DPATCH_VERSION=${{ github.run_number }}
+      
       - name: Build project
         run: cmake --build .
-      - name: Check .dmg file
-        run: test -f ./laba3-0.0.${{ github.run_number }}-macos.dmg
+
       - name: Create package
         run: cmake --build . --target package
+      
+      - name: Verify package creation
+        run: |
+          if [ ! -f ./laba3-0.0.${{ github.run_number }}-macos.dmg ]; then
+            echo "Error: .dmg file not found!" >&2
+            exit 1
+          fi
+
       - name: Create Release (macOS)
         id: create_release_macos
         uses: actions/create-release@v1
@@ -80,8 +93,9 @@ jobs:
           release_name: Release ${{ github.run_number }} (macOS)
           draft: false
           prerelease: false
+
       - name: Upload Release Asset (macOS)
-        id: upload-release-asset-macos
+        id: upload_release_asset_macos
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
